apiVersion: v1
kind: Service
metadata:
  name: obtener-calendario-service
spec:
  selector:
    app: obtener-calendario
  type: NodePort
  ports:
    - name: obtener-calendario
      protocol: TCP
      port: 5015
      targetPort: 5015  # Puerto del contenedor obtener-calendario
      nodePort: 30017   # Puerto asignado en los nodos del clúster