apiVersion: v1
kind: Service
metadata:
  name: obtener-usuario-service
spec:
  selector:
    app: obtener-usuario
  type: NodePort
  ports:
    - name: obtener-usuario
      protocol: TCP
      port: 5002
      targetPort: 5002  # Puerto del contenedor crear-usuario
      nodePort: 30005  # Puerto asignado en los nodos del clúster