apiVersion: apps/v1
kind: Deployment
metadata:
  name: obtener-reserva-puntual
spec:
  replicas: 1
  selector:
    matchLabels:
      app: obtener-reserva-puntual
  template:
    metadata:
      labels:
        app: obtener-reserva-puntual
    spec:
      containers:
      - name: obtener-reserva-puntual
        image: jusfb18/obtener-reserva-puntual:latest
        ports:
        - containerPort: 5014

