apiVersion: v1
kind: Service
metadata:
  name: obtener-reserva-puntual-service
spec:
  selector:
    app: obtener-reserva-puntual
  type: NodePort
  ports:
    - name: obtener-reserva-puntual
      protocol: TCP
      port: 5014
      targetPort: 5014  # Puerto del contenedor obtener-reserva-puntual
      nodePort: 30016   # Puerto asignado en los nodos del clúster