apiVersion: v1
kind: Service
metadata:
  name: obtener-reservas-todas-service
spec:
  selector:
    app: obtener-reservas-todas
  type: NodePort
  ports:
    - name: obtener-reservas-todas
      protocol: TCP
      port: 5011
      targetPort: 5011  # Puerto del contenedor crear-usuario
      nodePort: 30014  # Puerto asignado en los nodos del clúster