apiVersion: apps/v1
kind: Deployment
metadata:
  name: obtener-recomendacion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: obtener-recomendacion
  template:
    metadata:
      labels:
        app: obtener-recomendacion
    spec:
      containers:
      - name: obtener-recomendacion
        image: jusfb18/obtener-recomendacion:latest
        ports:
        - containerPort: 5018

