apiVersion: v1
kind: Service
metadata:
  name: obtener-recomendacion-service
spec:
  selector:
    app: obtener-recomendacion
  type: NodePort
  ports:
    - name: obtener-recomendacion
      protocol: TCP
      port: 5018
      targetPort: 5018  # Puerto del contenedor obtener-recomendacion
      nodePort: 30020   # Puerto asignado en los nodos del clúster