apiVersion: v1
kind: Service
metadata:
  name: obtener-reservas-service
spec:
  selector:
    app: obtener-reservas
  type: NodePort
  ports:
    - name: obtener-reservas
      protocol: TCP
      port: 5010
      targetPort: 5010  # Puerto del contenedor crear-usuario
      nodePort: 30014  # Puerto asignado en los nodos del clúster