apiVersion: v1
kind: Service
metadata:
  name: verificar-usuario-service
spec:
  selector:
    app: verificar-usuario
  type: NodePort
  ports:
    - name: verificar-usuario
      protocol: TCP
      port: 5003
      targetPort: 5003  # Puerto del contenedor crear-usuario
      nodePort: 30006