apiVersion: v1
kind: Service
metadata:
  name: obtener-reservas-futuras-service
spec:
  selector:
    app: obtener-reservas-futuras
  type: NodePort
  ports:
    - name: obtener-reservas-futuras
      protocol: TCP
      port: 5015
      targetPort: 5015  # Puerto del contenedor obtener-reservas-futuras
      nodePort: 30017  # Puerto asignado en los nodos del clúster