apiVersion: v1
kind: Service
metadata:
  name: eliminar-reserva-service
spec:
  selector:
    app: eliminar-reserva
  type: NodePort
  ports:
    - name: eliminar-reserva
      protocol: TCP
      port: 5010
      targetPort: 5010  # Puerto del contenedor eliminar-reserva
      nodePort: 30013  # Puerto asignado en los nodos del clúster