apiVersion: v1
kind: Service
metadata:
  name: editar-reserva-service
spec:
  selector:
    app: editar-reserva
  type: NodePort
  ports:
    - name: editar-reserva
      protocol: TCP
      port: 5009
      targetPort: 5009  # Puerto del contenedor crear-usuario
      nodePort: 30012  # Puerto asignado en los nodos del clúster