apiVersion: v1
kind: Service
metadata:
  name: crear-reserva-service
spec:
  selector:
    app: crear-reserva
  type: NodePort
  ports:
    - name: crear-reserva
      protocol: TCP
      port: 5007
      targetPort: 5007  # Puerto del contenedor crear-usuario
      nodePort: 30010  # Puerto asignado en los nodos del clúster