apiVersion: v1
kind: Service
metadata:
  name: broker-service
spec:
  selector:
    app: broker
  type: NodePort
  ports:
    - name: broker
      protocol: TCP
      port: 5016
      targetPort: 5016  # Puerto del contenedor obtener-calendario
      nodePort: 30018   # Puerto asignado en los nodos del clúster