apiVersion: v1
kind: Service
metadata:
  name: microrestaurant-service
spec:
  selector:
    app: microrestaurant
  type: NodePort
  ports:
    - name: crear-usuario
      protocol: TCP
      port: 5001
      targetPort: 5001  # Puerto del contenedor crear-usuario
      nodePort: 30004  # Puerto asignado en los nodos del clúster
    - name: obtener-usuario
      protocol: TCP
      port: 5002
      targetPort: 5002  # Puerto del contenedor crear-usuario
      nodePort: 30005  # Puerto asignado en los nodos del clúster
    - name: verificar-usuario
      protocol: TCP
      port: 5003
      targetPort: 5003  # Puerto del contenedor crear-usuario
      nodePort: 30006
    - name: cambiar-contrasena
      protocol: TCP
      port: 5004
      targetPort: 5004  # Puerto del contenedor crear-usuario
      nodePort: 30007  # Puerto asignado en los nodos del clúster