apiVersion: v1
kind: Service
metadata:
  name: crear-usuario-service
spec:
  selector:
    app: crear-usuario
  type: NodePort
  ports:
    - name: crear-usuario
      protocol: TCP
      port: 5001
      targetPort: 5001  # Puerto del contenedor crear-usuario
      nodePort: 30004  # Puerto asignado en los nodos del clúster